#!/usr/bin/env sh

# Switch keymap
super + alt + {1,2}
	setxkbmap {gb,dvorak}


## Starting/killing programs
# terminal

super + Return
    kitty

super + e
	kitty -e ranger

super + ctrl + c
	pkill picom ; picom -b --experimental-backends --use-damage

# Can't be shift, that's your shutdown stuff
control + super + e
	thunar

control + {_, shift +} Escape
	{htop, gotop}

# Rofi
super + d
	rofi -show drun -modi drun,run

super + alt + Tab
	rofi -show window -kb-row-down 'Down,Alt+Tab' -kb-accept-entry 'Return,!Alt_L,!Alt+Tab' -me-select-entry '' -me-accept-entry 'MousePrimary'
	
	# && maim | xclip -selection clipboard -t image/png -i
alt + Tab
	skippy-xd --activate-window-picker
###
# Deal with gaps at some point
###

## Brightness
super + {KP_Add,KP_Subtract}
	light {-A 10,-U 10}

## Audio controls
XF86Audio{RaiseVolume,LowerVolume}
	pactl set-sink-volume @DEFAULT_SINK@ {+,-}5%

XF86AudioMute
	pactl set-sink-mute @DEFAULT_SINK@ toggle


## Media controls
super + {apostrophe,comma,period}
	playerctl {play-pause,previous,next}

super + shift + {comma,period}
	playerctl position 5{-,+}


## Screenshots (you can clean this up, me)
# Select area
ctrl + @Print
	maim -s | xclip -selection clipboard -t image/png -i
# Current window
shift + @Print
	maim -i (xdotool getactivewindow) | xclip -selection clipboard -t image/png -i
# Whole desktop
@Print
	maim | xclip -selection clipboard -t image/png -i

# Lock
ctrl + super + l
	betterlockscreen -l

# Toggle polybar
super + b
	polybar-msg cmd toggle ; bspc config top_padding 0

super + shift + b
	sh ~/.config/polybar/launch.sh


## bspwm controls ##
# Quit/shutdown/reboot
super + shift + e ; {e,s,r,g}
	{bspc quit,systemctl poweroff,systemctl reboot,optimus-manager --switch auto --no-confirm}

# Restart
super + shift + r
	bspc wm -r

# Close/kill
super + shift + {q,x}
	bspc node -{c,k}

super + x
	xkill

# alternate between the tiled and monocle layout
super + f
	bspc desktop -l next

# toggle fullscreen of window
super + shift + f
	bspc node -t fullscreen

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

## State/flags
# set the window's tiledness
super + {_, ctrl, shift} + t
	bspc node -t {tiled,pseudo_tiled,floating}

# set the node flags
super + n ; {m,l,s,p}
	bspc node -g {marked,locked,sticky,private}

## Focus/swap
## focus the node in the given direction
super + {_,shift + ,ctrl + shift +}{Left,Down,Up,Right}
	bspc node -{f,s,n} {west,south,north,east} --follow

# focus the node for the given path jump
#super + {p,b,comma,period}
#	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + shift + alt + {Left,Right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

super + shift + button{4,5}
	bspc node -d {next,prev}.local --follow

# Win + mouse-scroll loops through desktops on monitor
super + ctrl + button{4,5}
    bspc desktop {next,prev}.local -f

# Win + mouse-scroll loops through occupied desktops on monitor
super + button{4,5}
    bspc desktop {next,prev}.occupied.local -f

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

### Bounce between a desktop, or if you are currently on that desktop, the last one
super + {1-9,0}
    desktop='^{1-9,10}'; \
    bspc query -D -d "$desktop.focused" && bspc desktop -f last || bspc desktop -f "$desktop"

# Send a window to a desktop
super + shift + {1-9,0}
	bspc node -d '^{1-9,10}'

super + w
	bspc monitor -f next

# Send to next active workspace (really, next monitor)
super + shift + w
	bspc node -d next.active; \
	bspc desktop -f next.active
#
# preselect
#
# preselect the direction
super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#
# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + ctrl + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

super + shift + Escape
    pkill -USR1 -x sxhkd ; notify-send "sxhkd config reloaded" -t 800 

# rotate the desktop, or the parent of selected node
super + {_,ctrl} + r
	bspc node @{/,parent} -R 90

# rotate the parent node's children


## Vim versions of all the moving stuff
# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + ctrl + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# focus the next/previous desktop in the current monitor
super + shift + alt + {h,l}
	bspc desktop -f {prev,next}.local

## focus the node in the given direction
super + {_,shift + ,ctrl + shift +}{h,j,k,l}
	bspc node -{f,s,n} {west,south,north,east} --follow

## This has no room for existence with the vim-y bindings, and I almost never use it, so... g'bye
# move a floating window
# super + {h,j,k,l}
#     bspc node -v {-20 0,0 20,0 -20,20 0}
